# The pipeline builds the Breezy project.

# trigger when branch 'master' changes
trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: Preparation
    steps:
    - task: GitVersion@5
      name: GitVersion_org
      displayName: 'Determine version number'
      inputs:
        runtime: 'core'
    - script: |
        # workaround until GitVersion integrates PR #2012 (https://github.com/GitTools/GitVersion/pull/2012)
        echo "##vso[task.setvariable variable=GitVersion.SemVer;isOutput=true]$(GitVersion.SemVer)"
        echo "##vso[task.setvariable variable=GitVersion.InformationalVersion;isOutput=true]$(GitVersion.InformationalVersion)"
      name: GitVersion
  - template: azure-pipelines.build-jobs.template
    parameters:
      toolchains:
      - name: i686-unknown-linux-musl
        buildSharedLibs: false
        buildStaticLibs: true
        buildStaticApps: true
      - name: i686-w64-mingw32
        buildSharedLibs: true
        buildStaticLibs: false
        buildStaticApps: false
      - name: x86_64-unknown-linux-musl
        buildSharedLibs: false
        buildStaticLibs: true
        buildStaticApps: true
      - name: x86_64-w64-mingw32
        buildSharedLibs: true
        buildStaticLibs: false
        buildStaticApps: false

- stage: Tests
  jobs:
  - job:
    displayName: breezy-linux-i686
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DownloadPipelineArtifact@2
      displayName: Download pipeline artifact
      inputs:
        source: current
        artifact: build-i686-unknown-linux-musl-Release
        path: $(Build.ArtifactStagingDirectory)
    - bash: |
        set -x
        mkdir -p ~/.local
        cd ~/.local
        tar -xvzf "$(Build.ArtifactStagingDirectory)/breezy.tar.gz"
        cd bin
        ./breezy_test --gtest_output=xml:$(Common.TestResultsDirectory)/TEST-breezy.xml
      displayName: Run Tests
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: JUnit
        testResultsFiles: $(Common.TestResultsDirectory)/TEST-*.xml
        failTaskOnFailedTests: true

  - job:
    displayName: breezy-linux-x86_x64
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DownloadPipelineArtifact@2
      displayName: Download pipeline artifact
      inputs:
        source: current
        artifact: build-x86_64-unknown-linux-musl-Release
        path: $(Build.ArtifactStagingDirectory)
    - bash: |
        set -x
        mkdir -p ~/.local
        cd ~/.local
        tar -xvzf "$(Build.ArtifactStagingDirectory)/breezy.tar.gz"
        cd bin
        ./breezy_test --gtest_output=xml:$(Common.TestResultsDirectory)/TEST-breezy.xml
      displayName: Run Tests
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: JUnit
        testResultsFiles: $(Common.TestResultsDirectory)/TEST-*.xml
        failTaskOnFailedTests: true

  - job:
    displayName: breezy-windows-i686
    pool:
      vmImage: windows-latest
    steps:
    - task: DownloadPipelineArtifact@2
      displayName: Download pipeline artifact
      inputs:
        source: current
        artifact: build-i686-w64-mingw32-Release
        path: $(Build.ArtifactStagingDirectory)
    - powershell: |
        New-Item -ItemType directory -Path $(Pipeline.Workspace)/breezy
        cd $(Pipeline.Workspace)/breezy
        Copy-Item -Path $(Build.ArtifactStagingDirectory)\breezy.tar.gz .
        tar -xzf breezy.tar.gz
        cd bin
        .\breezy_test.exe --gtest_output=xml:$(Common.TestResultsDirectory)/TEST-breezy.xml
      displayName: Run Tests
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: JUnit
        testResultsFiles: $(Common.TestResultsDirectory)\TEST-*.xml
        failTaskOnFailedTests: true

  - job:
    displayName: breezy-windows-x86_x64
    pool:
      vmImage: windows-latest
    steps:
    - task: DownloadPipelineArtifact@2
      displayName: Download pipeline artifact
      inputs:
        source: current
        artifact: build-x86_64-w64-mingw32-Release
        path: $(Build.ArtifactStagingDirectory)
    - powershell: |
        New-Item -ItemType directory -Path $(Pipeline.Workspace)/breezy
        cd $(Pipeline.Workspace)/breezy
        Copy-Item -Path $(Build.ArtifactStagingDirectory)\breezy.tar.gz .
        tar -xzf breezy.tar.gz
        cd bin
        .\breezy_test.exe --gtest_output=xml:$(Common.TestResultsDirectory)/TEST-breezy.xml
      displayName: Run Tests
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: JUnit
        testResultsFiles: $(Common.TestResultsDirectory)/TEST-*.xml
        failTaskOnFailedTests: true
